from microdot import *
from _typeshed import Incomplete
from microdot.microdot import Microdot as BaseMicrodot, NoCaseDict as NoCaseDict, Request as Request, Response as Response, abort as abort
from microdot.websocket import WebSocket as BaseWebSocket, websocket_wrapper as websocket_wrapper

class _BodyStream:
    receive: Incomplete
    data: bytes
    more: bool
    def __init__(self, receive) -> None: ...
    async def read_more(self) -> None: ...
    async def read(self, n: int = -1): ...
    async def readline(self): ...
    async def readexactly(self, n): ...
    async def readuntil(self, separator: bytes = b'\n'): ...

class Microdot(BaseMicrodot):
    lifespan_startup: Incomplete
    lifespan_shutdown: Incomplete
    embedded_server: bool
    def __init__(self, lifespan_startup=None, lifespan_shutdown=None) -> None: ...
    async def handle_lifespan(self, scope, receive, send) -> None: ...
    async def asgi_app(self, scope, receive, send): ...
    async def __call__(self, scope, receive, send): ...
    def shutdown(self) -> None: ...
    def run(self, host: str = '0.0.0.0', port: int = 5000, debug: bool = False, **options) -> None: ...

class WebSocket(BaseWebSocket):
    async def handshake(self) -> None: ...
    async def receive(self): ...
    async def send(self, data) -> None: ...
    closed: bool
    async def close(self) -> None: ...

async def websocket_upgrade(request): ...
def with_websocket(f): ...
