from _typeshed import Incomplete
from microdot import abort as abort
from microdot.microdot import invoke_handler as invoke_handler

class BaseAuth:
    auth_callback: Incomplete
    error_callback: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, f): ...
    def optional(self, f): ...

class BasicAuth(BaseAuth):
    realm: Incomplete
    charset: Incomplete
    scheme: Incomplete
    error_status: Incomplete
    error_callback: Incomplete
    def __init__(self, realm: str = 'Please login', charset: str = 'UTF-8', scheme: str = 'Basic', error_status: int = 401) -> None: ...
    async def authentication_error(self, request): ...
    auth_callback: Incomplete
    def authenticate(self, f) -> None: ...

class TokenAuth(BaseAuth):
    header: Incomplete
    scheme: Incomplete
    error_status: Incomplete
    error_callback: Incomplete
    def __init__(self, header: str = 'Authorization', scheme: str = 'Bearer', error_status: int = 401) -> None: ...
    auth_callback: Incomplete
    def authenticate(self, f) -> None: ...
    def errorhandler(self, f) -> None: ...
    async def authentication_error(self, request) -> None: ...
