from _typeshed import Incomplete

class CORS:
    allowed_origins: Incomplete
    allow_credentials: Incomplete
    allowed_methods: Incomplete
    expose_headers: Incomplete
    allowed_headers: Incomplete
    max_age: Incomplete
    def __init__(self, app=None, allowed_origins=None, allow_credentials: bool = False, allowed_methods=None, expose_headers=None, allowed_headers=None, max_age=None, handle_cors: bool = True) -> None: ...
    default_options_handler: Incomplete
    def initialize(self, app, handle_cors: bool = True) -> None: ...
    def options_handler(self, request): ...
    def get_cors_headers(self, request): ...
    def after_request(self, request, response) -> None: ...
