from _typeshed import Incomplete

class Template:
    jinja_env: Incomplete
    @classmethod
    def initialize(cls, template_dir: str = 'templates', enable_async: bool = False, **kwargs) -> None: ...
    name: Incomplete
    template: Incomplete
    def __init__(self, template, **kwargs) -> None: ...
    def generate(self, *args, **kwargs): ...
    def render(self, *args, **kwargs): ...
    def generate_async(self, *args, **kwargs): ...
    async def render_async(self, *args, **kwargs): ...
