from _typeshed import Incomplete
from microdot import redirect as redirect
from microdot.microdot import invoke_handler as invoke_handler, urlencode as urlencode

class Login:
    login_url: Incomplete
    user_loader_callback: Incomplete
    def __init__(self, login_url: str = '/login') -> None: ...
    def user_loader(self, f) -> None: ...
    async def login_user(self, request, user, remember: bool = False, redirect_url: str = '/'): ...
    async def logout_user(self, request) -> None: ...
    async def get_current_user(self, request): ...
    def __call__(self, f): ...
    def fresh(self, f): ...
