from _typeshed import Incomplete

async def invoke_handler(handler, *args, **kwargs): ...

MUTED_SOCKET_ERRORS: Incomplete

def urldecode(s): ...
def urlencode(s): ...

class NoCaseDict(dict):
    keymap: Incomplete
    def __init__(self, initial_dict=None) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def get(self, key, default=None): ...
    def update(self, other_dict) -> None: ...

def mro(cls): ...

class MultiDict(dict):
    def __init__(self, initial_dict=None) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def get(self, key, default=None, type=None): ...
    def getlist(self, key, type=None): ...

class AsyncBytesIO:
    stream: Incomplete
    def __init__(self, data) -> None: ...
    async def read(self, n: int = -1): ...
    async def readline(self): ...
    async def readexactly(self, n): ...
    async def readuntil(self, separator: bytes = b'\n'): ...
    async def awrite(self, data): ...
    async def aclose(self) -> None: ...

class Request:
    max_content_length: Incomplete
    max_body_length: Incomplete
    max_readline: Incomplete
    class G: ...
    app: Incomplete
    client_addr: Incomplete
    method: Incomplete
    scheme: Incomplete
    url: Incomplete
    url_prefix: Incomplete
    subapp: Incomplete
    route: Incomplete
    path: Incomplete
    query_string: Incomplete
    args: Incomplete
    headers: Incomplete
    cookies: Incomplete
    content_length: int
    content_type: Incomplete
    g: Incomplete
    http_version: Incomplete
    body_used: bool
    sock: Incomplete
    after_request_handlers: Incomplete
    def __init__(self, app, client_addr, method, url, http_version, headers, body=None, stream=None, sock=None, url_prefix: str = '', subapp=None, scheme=None, route=None) -> None: ...
    @staticmethod
    async def create(app, client_reader, client_writer, client_addr, scheme=None): ...
    @property
    def body(self): ...
    @property
    def stream(self): ...
    @property
    def json(self): ...
    @property
    def form(self): ...
    @property
    def files(self): ...
    def after_request(self, f): ...

class Response:
    types_map: Incomplete
    send_file_buffer_size: int
    default_content_type: str
    default_send_file_max_age: Incomplete
    already_handled: Incomplete
    status_code: Incomplete
    headers: Incomplete
    reason: Incomplete
    body: Incomplete
    is_head: bool
    def __init__(self, body: bytes = b'', status_code: int = 200, headers=None, reason=None) -> None: ...
    def set_cookie(self, cookie, value, path=None, domain=None, expires=None, max_age=None, secure: bool = False, http_only: bool = False, partitioned: bool = False) -> None: ...
    def delete_cookie(self, cookie, **kwargs) -> None: ...
    def complete(self) -> None: ...
    async def write(self, stream) -> None: ...
    i: Incomplete
    def body_iter(self): ...
    @classmethod
    def redirect(cls, location, status_code: int = 302): ...
    @classmethod
    def send_file(cls, filename, status_code: int = 200, content_type=None, stream=None, max_age=None, compressed: bool = False, file_extension: str = ''): ...

class URLPattern:
    segment_patterns: Incomplete
    segment_parsers: Incomplete
    @classmethod
    def register_type(cls, type_name, pattern: str = '[^/]+', parser=None) -> None: ...
    url_pattern: Incomplete
    segments: Incomplete
    regex: Incomplete
    def __init__(self, url_pattern) -> None: ...
    def compile(self): ...
    def match(self, path): ...

class HTTPException(Exception):
    status_code: Incomplete
    reason: Incomplete
    def __init__(self, status_code, reason=None) -> None: ...

class Microdot:
    url_map: Incomplete
    before_request_handlers: Incomplete
    after_request_handlers: Incomplete
    after_error_request_handlers: Incomplete
    error_handlers: Incomplete
    options_handler: Incomplete
    ssl: bool
    debug: bool
    server: Incomplete
    def __init__(self) -> None: ...
    def route(self, url_pattern, methods=None): ...
    def get(self, url_pattern): ...
    def post(self, url_pattern): ...
    def put(self, url_pattern): ...
    def patch(self, url_pattern): ...
    def delete(self, url_pattern): ...
    def before_request(self, f): ...
    def after_request(self, f): ...
    def after_error_request(self, f): ...
    def errorhandler(self, status_code_or_exception_class): ...
    def mount(self, subapp, url_prefix: str = '', local: bool = False) -> None: ...
    @staticmethod
    def abort(status_code, reason=None) -> None: ...
    async def start_server(self, host: str = '0.0.0.0', port: int = 5000, debug: bool = False, ssl=None, start_serving: bool = True): ...
    def run(self, host: str = '0.0.0.0', port: int = 5000, debug: bool = False, ssl=None) -> None: ...
    def shutdown(self) -> None: ...
    def find_route(self, req): ...
    def default_options_handler(self, req): ...
    async def handle_request(self, reader, writer) -> None: ...
    def get_request_handlers(self, req, attr, local_first: bool = True): ...
    async def error_response(self, req, status_code, reason=None): ...
    async def dispatch_request(self, req): ...

abort: Incomplete
redirect: Incomplete
send_file: Incomplete
