from _typeshed import Incomplete
from microdot import AsyncBytesIO as AsyncBytesIO, abort as abort, iscoroutine as iscoroutine
from microdot.helpers import wraps as wraps

class FormDataIter:
    buffer_size: int
    request: Incomplete
    buffer: Incomplete
    boundary: Incomplete
    extra_size: Incomplete
    def __init__(self, request) -> None: ...
    def __aiter__(self): ...
    async def __anext__(self): ...

class FileUpload:
    max_memory_size: int
    filename: Incomplete
    content_type: Incomplete
    def __init__(self, filename, content_type, read) -> None: ...
    async def read(self, n: int = -1): ...
    async def save(self, path_or_file) -> None: ...
    async def copy(self, max_memory_size=None): ...
    async def close(self) -> None: ...

def with_form_data(f): ...
