from _typeshed import Incomplete
from microdot.helpers import wraps as wraps
from microdot.microdot import invoke_handler as invoke_handler

class SessionDict(dict):
    request: Incomplete
    def __init__(self, request, session_dict) -> None: ...
    def save(self) -> None: ...
    def delete(self) -> None: ...

class Session:
    secret_key: Incomplete
    cookie_options: Incomplete
    def __init__(self, app=None, secret_key=None, cookie_options=None) -> None: ...
    def initialize(self, app, secret_key=None, cookie_options=None) -> None: ...
    def get(self, request): ...
    def update(self, request, session): ...
    def delete(self, request): ...
    def encode(self, payload, secret_key=None): ...
    def decode(self, session, secret_key=None): ...

def with_session(f): ...
