from _typeshed import Incomplete
from microdot.helpers import wraps as wraps

class SSE:
    event: Incomplete
    queue: Incomplete
    def __init__(self) -> None: ...
    async def send(self, data, event=None, event_id=None, retry=None, comment: bool = False) -> None: ...

def sse_response(request, event_function, *args, **kwargs): ...
def with_sse(f): ...
