from _typeshed import Incomplete

class Template:
    @classmethod
    def initialize(cls, template_dir: str = 'templates', loader_class=...) -> None: ...
    name: Incomplete
    template: Incomplete
    def __init__(self, template) -> None: ...
    def generate(self, *args, **kwargs): ...
    def render(self, *args, **kwargs): ...
    iter: Incomplete
    def generate_async(self, *args, **kwargs): ...
    async def render_async(self, *args, **kwargs): ...
