from _typeshed import Incomplete
from microdot import Request as Request, Response as Response
from microdot.helpers import wraps as wraps
from microdot.microdot import MUTED_SOCKET_ERRORS as MUTED_SOCKET_ERRORS, print_exception as print_exception

class WebSocketError(Exception): ...

class WebSocket:
    CONT: int
    TEXT: int
    BINARY: int
    CLOSE: int
    PING: int
    PONG: int
    max_message_length: int
    request: Incomplete
    closed: bool
    def __init__(self, request) -> None: ...
    async def handshake(self) -> None: ...
    async def receive(self): ...
    async def send(self, data, opcode=None) -> None: ...
    async def close(self) -> None: ...

async def websocket_upgrade(request): ...
def websocket_wrapper(f, upgrade_function): ...
def with_websocket(f): ...
