from microdot import *
from _typeshed import Incomplete
from microdot.microdot import MUTED_SOCKET_ERRORS as MUTED_SOCKET_ERRORS, Microdot as BaseMicrodot, NoCaseDict as NoCaseDict, Request as Request
from microdot.websocket import WebSocket as WebSocket, websocket_upgrade as websocket_upgrade, with_websocket as with_websocket

class Microdot(BaseMicrodot):
    loop: Incomplete
    embedded_server: bool
    def __init__(self) -> None: ...
    wsgi_input: Incomplete
    iter: Incomplete
    def wsgi_app(self, environ, start_response): ...
    def __call__(self, environ, start_response): ...
    def shutdown(self) -> None: ...
    def run(self, host: str = '0.0.0.0', port: int = 5000, debug: bool = False, **options) -> None: ...
